### ISSUE TITLE
Need to load tokens to device

### ISSUE THREAD

**Issue by bibhas2** [rasbt/LLM-workshop-2024#6]
In ``04.ipynb``, for **Solution to Exercise 1**, the token IDs need to be loaded into the device. Otherwise, in a GPU machine where the model was previously loaded into the GPU there will be a device mismatch error. So, the relevant line should be:

```python
idx=text_to_token_ids(start_context, tokenizer).to(device),
```

Error message without the above fix:

```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! 
(when checking argument for argument index in method wrapper_CUDA__index_select)
```

**Comment by rasbt** [comment]
Thanks for the note. I agree and added this.
